AI Programming

In [64]:
import numpy as np
np.__version__


'1.26.1'

# Exercise 1: Creating and Manipulating NumPy Arrays


* Create a 1D NumPy array from the list [5, 10, 15, 20, 25]. Convert the array to type float64 and print it.

In [65]:
l = [5, 10, 15, 20, 25]

v = np.array(l, dtype=np.float64)

v

array([ 5., 10., 15., 20., 25.])


* Create a 2D NumPy array from the nested list [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Print the shape and size of the array.

In [89]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

v = np.array(l, dtype=np.float64)

print("shape : " , v.shape, "\nlen : ", v.size)


shape :  (3, 3) 
len :  9


* Create a 3D NumPy array with random values of shape (2, 3, 4). Print the number of dimensions and the shape of the array.

In [67]:
l = np.random.randn(2 * 3 * 4)

print("N dimensions : ", l.ndim, ", shape : ", l.shape)

N dimensions :  1 , shape :  (24,)


# Exercise 3: Advanced Array Manipulations

* Create a 1D NumPy array with the numbers from 0 to 9. Reverse the array and print it.

In [68]:
l = np.arange(0, 10)
v = np.flip(l)

v

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

* Create a 2D NumPy array with the numbers from 0 to 11, arranged in a 3x4 shape. Extract a subarray consisting of the first two rows and the last two columns, and print it.

In [69]:
l = np.arange(0, 12).reshape(3,4)
rows, col = l.shape
# print(l)

new_l = l[0:2] 
new_l[:, [rows-1, rows]]

array([[2, 3],
       [6, 7]])

* Create a 2D NumPy array of shape (5, 5) with random integers between 0 and 10. Replace all elements greater than 5 with 0 and print the modified array.

In [74]:
l =  np.random.randint(0, 11, size=(5,5))

l[l > 5] = 0

l

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 5, 3],
       [0, 0, 1, 0, 0],
       [0, 2, 5, 2, 0],
       [0, 2, 0, 0, 0]])

# Exercise 4: Array Initialization and Attributes
* Create a 3x3 identity matrix using NumPy and print its attributes: ndim, shape, size, itemsize, and nbytes.

In [85]:
i = np.identity(3)

print("n dimensions :", i.ndim, "\nshape: ", i.shape, "\nitemsize : ", i.itemsize, "\nn bytes : ", i.nbytes)

n dimensions : 2 
shape:  (3, 3) 
itemsize :  8 
n bytes :  72


* Create an array of 10 evenly spaced numbers between 0 and 5 using numpy.linspace(). Print the array and its datatype.

In [86]:
l = np.linspace( 0, 5, 10)

print("array :\n", l)
print("datatype : ", l.dtype)

array :
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
datatype :  float64


* Create a 3D array of shape (2, 3, 4) with random values from a standard normal distribution. Print the array and the sum of all elements.


In [87]:
l = np.random.randn(2, 3, 4)

print("array :\n", l)

l_sum = np.sum(l)
print("Sum of all elements:", l_sum)

array :
 [[[-0.9354861  -0.39484894 -0.07432171  0.85838908]
  [ 0.59338049 -0.79315059 -0.01796395 -0.01843861]
  [ 0.31809958 -0.88561968  0.36654509  0.03763287]]

 [[-0.42174477  0.29720986  0.28203506 -0.2695184 ]
  [-0.64737608  0.15484662 -1.52567553  0.14138236]
  [-1.30874923 -0.03169172 -1.63725781 -0.68210365]]]
Sum of all elements: -6.5944257423787285


# Exercise 5: Fancy Indexing and Masking
* Create a 1D NumPy array with random integers between 0 and 50 of size 20. Use fancy indexing to extract elements at indices [2, 5, 7, 10, 15] and print them.

In [93]:
l = np.random.randint(0, 50, size=20)

indices = [2, 5, 7, 10, 15]

print("Extracted elements: ", l[indices])

Extracted elements:  [30 11 18 26 27]


* Create a 2D NumPy array with random integers between 0 and 30 of shape (4, 5). Use a boolean mask to select all elements greater than 15 and print them.


In [108]:
l = np.random.randint(0, 30, size=(4,5))

l[l > 15]

array([22, 18, 16, 25, 28, 28, 21, 26, 22, 29])

* Create a 1D NumPy array of 10 random integers between -10 and 10. Use a boolean mask to set all negative values to zero and print the modified array.

In [113]:
l = np.random.randint(-10, 10, size=10)

l[l < 0] = 0

l

array([0, 3, 0, 6, 0, 8, 0, 8, 3, 2])

# Exercise 7: Combining and Splitting Arrays
* Create two 1D NumPy arrays of length 5 with random integers between 0 and 10. Concatenate the two arrays and print the result.

In [115]:
la = np.random.randint(0, 5, size=5)
lb= np.random.randint(0, 5, size=5)

new_l = np.concatenate((la, lb))

new_l

array([4, 4, 0, 4, 2, 1, 3, 3, 1, 4])

* Create a 2D NumPy array of shape (6, 4) with random integers between 0 and 10. Split the array into two equal parts along the row axis and print them.

In [121]:
l = np.random.randint(0, 10, size=(6,4))

np.split(l, 2, axis=0)

[array([[5, 7, 4, 2],
        [6, 0, 8, 5],
        [2, 8, 0, 4]]),
 array([[8, 6, 7, 1],
        [2, 6, 8, 7],
        [0, 7, 1, 3]])]

* Create a 2D NumPy array of shape (3, 6) with random integers between 0 and 10. Split the array into three equal parts along the column axis and print them.

In [123]:
l = np.random.randint(0, 10, size=(3,6))

np.hsplit(l, 3)

[array([[0, 9],
        [0, 9],
        [6, 0]]),
 array([[2, 1],
        [3, 8],
        [6, 1]]),
 array([[8, 1],
        [1, 3],
        [1, 3]])]

# Exercise 8: Mathematical Functions and Aggregations
* Create a 1D NumPy array with random integers between 1 and 100 of size 15. Compute and print the mean, median, standard deviation, and variance of the array.

In [126]:
l = np.random.randint(1, 100, size=15)

mean = np.mean(l)
median = np.median(l)
std_dev = np.std(l)
variance = np.var(l)

print("array :\n", l)
print("mean:", mean)
print("median:", median)
print("standard deviation:", std_dev)
print("variance:", variance)

array :
 [92 73  8 29 53 18 91 77 56 38 33 72 89 89 24]
mean: 56.13333333333333
median: 56.0
standard deviation: 28.340469689513302
variance: 803.1822222222222


* Create a 2D NumPy array of shape (4, 4) with random integers between 1 and 50. Compute and print the sum of each row and each column.

In [129]:
l = np.random.randint(1, 50, size=(4,4))

sum_row = np.sum(l, axis=1)

sum_col = np.sum(l, axis=0)
print("sum row ", sum_row)
print("sum col ", sum_col)


sum row  [118  89  89 125]
sum col  [135 107 105  74]


* Create a 3D NumPy array of shape (2, 3, 4) with random integers between 1 and 20. Find the maximum and minimum values along each axis and print them.

In [132]:
l = np.random.randint(1, 21, size=(2, 3, 4))

for x in l:
    print(x)

print("axe 0 min : ", np.min(l, axis = 0))


[[ 2 20 15 16]
 [ 6  4  2  6]
 [16 12 14  7]]
[[15 19  9  3]
 [ 6 20 16  9]
 [ 6 20 14 14]]
axe 0 min :  [[ 2 19  9  3]
 [ 6  4  2  6]
 [ 6 12 14  7]]


# Exercise 9: Reshaping and Transposing Arrays
* Create a 1D NumPy array with the numbers from 1 to 12. Reshape the array to a 2D array of shape (3, 4) and print it.

* Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Transpose the array and print the transposed array.

* Create a 2D NumPy array of shape (2, 3) with random integers between 1 and 10. Flatten the array to 1D and print the result.

# Exercise 10: Broadcasting and Vectorized Operations
* Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Subtract the mean of each column from the respective column elements and print the result.

* Create two 1D NumPy arrays of length 4 with random integers between 1 and 5. Use broadcasting to compute and print the outer product of the two arrays.

* Create a 2D NumPy array of shape (4, 5) with random integers between 1 and 10. Add 10 to all elements of the array that are greater than 5 and print the modified array.

# Exercise 11: Sorting and Searching Arrays
* Create a 1D NumPy array with random integers between 1 and 20 of size 10. Sort the array in ascending order and print the sorted array.

* Create a 2D NumPy array of shape (3, 5) with random integers between 1 and 50. Sort the array by the second column and print the result.

* Create a 1D NumPy array with random integers between 1 and 100 of size 15. Find and print the indices of all elements greater than 50.