AI Programming

In [3]:
import numpy as np
np.__version__


'1.26.1'

# Exercise 1: Creating and Manipulating NumPy Arrays


* Create a 1D NumPy array from the list [5, 10, 15, 20, 25]. Convert the array to type float64 and print it.

In [4]:
l = [5, 10, 15, 20, 25]

v = np.array(l, dtype=np.float64)

v

array([ 5., 10., 15., 20., 25.])


* Create a 2D NumPy array from the nested list [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Print the shape and size of the array.

In [5]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

v = np.array(l, dtype=np.float64)

print("shape : " , v.shape, "\nlen : ", v.size)


shape :  (3, 3) 
len :  9


* Create a 3D NumPy array with random values of shape (2, 3, 4). Print the number of dimensions and the shape of the array.

In [6]:
l = np.random.randn(2 * 3 * 4)

print("N dimensions : ", l.ndim, ", shape : ", l.shape)

N dimensions :  1 , shape :  (24,)


# Exercise 3: Advanced Array Manipulations

* Create a 1D NumPy array with the numbers from 0 to 9. Reverse the array and print it.

In [7]:
l = np.arange(0, 10)
v = np.flip(l)

v

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

* Create a 2D NumPy array with the numbers from 0 to 11, arranged in a 3x4 shape. Extract a subarray consisting of the first two rows and the last two columns, and print it.

In [8]:
l = np.arange(0, 12).reshape(3,4)
rows, col = l.shape
# print(l)

new_l = l[0:2] 
new_l[:, [rows-1, rows]]

array([[2, 3],
       [6, 7]])

* Create a 2D NumPy array of shape (5, 5) with random integers between 0 and 10. Replace all elements greater than 5 with 0 and print the modified array.

In [9]:
l =  np.random.randint(0, 11, size=(5,5))

l[l > 5] = 0

l

array([[0, 5, 0, 2, 0],
       [0, 0, 5, 0, 0],
       [0, 1, 3, 4, 0],
       [1, 0, 1, 5, 0],
       [0, 0, 5, 0, 3]])

# Exercise 4: Array Initialization and Attributes
* Create a 3x3 identity matrix using NumPy and print its attributes: ndim, shape, size, itemsize, and nbytes.

In [10]:
i = np.identity(3)

print("n dimensions :", i.ndim, "\nshape: ", i.shape, "\nitemsize : ", i.itemsize, "\nn bytes : ", i.nbytes)

n dimensions : 2 
shape:  (3, 3) 
itemsize :  8 
n bytes :  72


* Create an array of 10 evenly spaced numbers between 0 and 5 using numpy.linspace(). Print the array and its datatype.

In [11]:
l = np.linspace( 0, 5, 10)

print("array :\n", l)
print("datatype : ", l.dtype)

array :
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
datatype :  float64


* Create a 3D array of shape (2, 3, 4) with random values from a standard normal distribution. Print the array and the sum of all elements.


In [12]:
l = np.random.randn(2, 3, 4)

print("array :\n", l)

l_sum = np.sum(l)
print("Sum of all elements:", l_sum)

array :
 [[[-1.3566016  -1.30153022 -0.44542548  0.35949516]
  [-0.24053512  0.39705902  0.74080932 -0.68232073]
  [ 0.04920872  0.1579356   0.09829851  0.36047666]]

 [[ 1.57490593 -1.30807777  0.1843341  -0.04767441]
  [ 1.22462913 -0.78151853 -0.80727735  0.897909  ]
  [-0.79109412 -0.56564903 -1.00527989 -0.1818915 ]]]
Sum of all elements: -3.4698146045290166


# Exercise 5: Fancy Indexing and Masking
* Create a 1D NumPy array with random integers between 0 and 50 of size 20. Use fancy indexing to extract elements at indices [2, 5, 7, 10, 15] and print them.

In [13]:
l = np.random.randint(0, 50, size=20)

indices = [2, 5, 7, 10, 15]

print("Extracted elements: ", l[indices])

Extracted elements:  [ 2 41 22  3 19]


* Create a 2D NumPy array with random integers between 0 and 30 of shape (4, 5). Use a boolean mask to select all elements greater than 15 and print them.


In [14]:
l = np.random.randint(0, 30, size=(4,5))

l[l > 15]

array([26, 20, 28, 22, 20, 20, 28, 18, 25, 28, 22])

* Create a 1D NumPy array of 10 random integers between -10 and 10. Use a boolean mask to set all negative values to zero and print the modified array.

In [15]:
l = np.random.randint(-10, 10, size=10)

l[l < 0] = 0

l

array([6, 0, 7, 0, 0, 0, 1, 0, 0, 2])

# Exercise 7: Combining and Splitting Arrays
* Create two 1D NumPy arrays of length 5 with random integers between 0 and 10. Concatenate the two arrays and print the result.

In [16]:
la = np.random.randint(0, 5, size=5)
lb= np.random.randint(0, 5, size=5)

new_l = np.concatenate((la, lb))

new_l

array([0, 4, 2, 3, 3, 0, 4, 3, 1, 2])

* Create a 2D NumPy array of shape (6, 4) with random integers between 0 and 10. Split the array into two equal parts along the row axis and print them.

In [17]:
l = np.random.randint(0, 10, size=(6,4))

np.split(l, 2, axis=0)

[array([[1, 7, 1, 8],
        [1, 9, 2, 4],
        [2, 2, 1, 2]]),
 array([[5, 9, 4, 8],
        [9, 9, 0, 6],
        [2, 9, 4, 1]])]

* Create a 2D NumPy array of shape (3, 6) with random integers between 0 and 10. Split the array into three equal parts along the column axis and print them.

In [18]:
l = np.random.randint(0, 10, size=(3,6))

np.hsplit(l, 3)

[array([[1, 8],
        [1, 2],
        [5, 1]]),
 array([[6, 7],
        [7, 9],
        [6, 2]]),
 array([[6, 4],
        [1, 6],
        [6, 2]])]

# Exercise 8: Mathematical Functions and Aggregations
* Create a 1D NumPy array with random integers between 1 and 100 of size 15. Compute and print the mean, median, standard deviation, and variance of the array.

In [19]:
l = np.random.randint(1, 100, size=15)

mean = np.mean(l)
median = np.median(l)
std_dev = np.std(l)
variance = np.var(l)

print("array :\n", l)
print("mean:", mean)
print("median:", median)
print("standard deviation:", std_dev)
print("variance:", variance)

array :
 [40 46 68 47 37 49 15 93 89 72 39 97  3 77 33]
mean: 53.666666666666664
median: 47.0
standard deviation: 27.145697428669777
variance: 736.888888888889


* Create a 2D NumPy array of shape (4, 4) with random integers between 1 and 50. Compute and print the sum of each row and each column.

In [20]:
l = np.random.randint(1, 50, size=(4,4))

sum_row = np.sum(l, axis=1)

sum_col = np.sum(l, axis=0)
print("sum row ", sum_row)
print("sum col ", sum_col)


sum row  [ 67 128 136 106]
sum col  [103  96 135 103]


* Create a 3D NumPy array of shape (2, 3, 4) with random integers between 1 and 20. Find the maximum and minimum values along each axis and print them.

In [21]:
l = np.random.randint(1, 21, size=(2, 3, 4))

for x in l:
    print(x)

print("axe 0 min : ", np.min(l, axis = 0))


[[ 5 14 17 11]
 [ 4  5 16  5]
 [16  3  5 18]]
[[ 6 19  6  3]
 [17 10  2  6]
 [16  7  7 11]]
axe 0 min :  [[ 5 14  6  3]
 [ 4  5  2  5]
 [16  3  5 11]]


# Exercise 9: Reshaping and Transposing Arrays
* Create a 1D NumPy array with the numbers from 1 to 12. Reshape the array to a 2D array of shape (3, 4) and print it.

In [22]:
l = np.arange(1,13)
l = l.reshape((3,4))
l


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

* Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Transpose the array and print the transposed array.

In [23]:
l = np.random.randint(1, 11, size=(3,4))

print(np.transpose(l))

[[9 8 2]
 [5 3 7]
 [6 7 9]
 [6 1 5]]


* Create a 2D NumPy array of shape (2, 3) with random integers between 1 and 10. Flatten the array to 1D and print the result.

In [24]:
l = np.random.randint(1, 11, size=(2,3))

print(l.flatten())


[10  4 10  7 10  9]


# Exercise 10: Broadcasting and Vectorized Operations
* Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Subtract the mean of each column from the respective column elements and print the result.

In [25]:
l = np.random.randint(1, 11, size=(3,4))

column_means = np.mean(l, axis=0)

r = l - column_means
print(r)


[[-1.33333333  0.66666667  1.         -2.66666667]
 [-0.33333333 -1.33333333 -3.         -2.66666667]
 [ 1.66666667  0.66666667  2.          5.33333333]]


* Create two 1D NumPy arrays of length 4 with random integers between 1 and 5. Use broadcasting to compute and print the outer product of the two arrays.

In [26]:
l = np.random.randint(1, 6, size=4)
l2 = np.random.randint(1, 6, size=4)


print("Array 1:", l)
print("Array 2:", l2)
np.outer(l, l2)

Array 1: [5 4 4 2]
Array 2: [2 5 5 5]


array([[10, 25, 25, 25],
       [ 8, 20, 20, 20],
       [ 8, 20, 20, 20],
       [ 4, 10, 10, 10]])

* Create a 2D NumPy array of shape (4, 5) with random integers between 1 and 10. Add 10 to all elements of the array that are greater than 5 and print the modified array.

In [27]:
l = np.random.randint(1,11,size=(4,5))
print(l)
l[l>5] = 10
print(l)


[[ 5  8 10  1  2]
 [ 3  2  2  7  6]
 [ 1  6  1  9  3]
 [ 8  1  1  7  6]]
[[ 5 10 10  1  2]
 [ 3  2  2 10 10]
 [ 1 10  1 10  3]
 [10  1  1 10 10]]


# Exercise 11: Sorting and Searching Arrays
* Create a 1D NumPy array with random integers between 1 and 20 of size 10. Sort the array in ascending order and print the sorted array.

In [28]:
l = np.random.randint(1,11,size=10)

print(l)

print(np.sort(l))

[ 2  9  1 10  5  1  5  7  1  1]
[ 1  1  1  1  2  5  5  7  9 10]


* Create a 2D NumPy array of shape (3, 5) with random integers between 1 and 50. Sort the array by the second column and print the result.

In [29]:
l = np.random.randint(1, 51, size=(3,5))

print(l)
print(l[l[:, 1].argsort()])


[[34 44 50 10 50]
 [35 36  9 43 14]
 [15 28 17 27 19]]
[[15 28 17 27 19]
 [35 36  9 43 14]
 [34 44 50 10 50]]


* Create a 1D NumPy array with random integers between 1 and 100 of size 15. Find and print the indices of all elements greater than 50.

In [30]:
l = np.random.randint(1, 101, size=15)
print(l)
print(l[l > 50])

[29 74 72  3 78 28 94 45 95 64 18 84 86 32 21]
[74 72 78 94 95 64 84 86]


# Exercise 12: Linear Algebra with NumPy
* Create a 2D NumPy array of shape (2, 2) with random integers between 1 and 10. Compute and print the determinant of the array.

In [31]:
l = np.random.randint(1, 11, size=(2,2))

print(l)
print(np.linalg.det(l))


[[9 4]
 [8 8]]
40.000000000000014


* Create a 2D NumPy array of shape (3, 3) with random integers between 1 and 5. Compute and print the eigenvalues and eigenvectors of the array.

In [32]:
l = np.random.randint(1, 6, size=(3, 3))
print(l)
eigenvalues, eigenvectors = np.linalg.eig(l)
print(eigenvalues)
print(eigenvectors)

[[3 5 4]
 [4 1 3]
 [3 1 2]]
[ 8.80358001 -2.53469525 -0.26888476]
[[ 0.74082348  0.75615844 -0.50374503]
 [ 0.5355799  -0.53039302 -0.31436137]
 [ 0.40538222 -0.38328536  0.80462282]]


* Create two 2D NumPy arrays of shape (2, 3) and (3, 2) with random integers between 1 and 10. Compute and print the matrix product of the two arrays.

In [33]:
l = np.random.randint(1, 10, size=(2,3))
l2 = np.random.randint(1, 10, size=(3,2))

print(l)
print(l2)

print("matrix product : ", np.matmul(l, l2))



[[9 9 7]
 [2 1 2]]
[[8 9]
 [7 8]
 [2 2]]
matrix product :  [[149 167]
 [ 27  30]]


# Exercise 13: Random Sampling and Distributions
* Create a 1D NumPy array of 10 random samples from a uniform distribution over [0, 1) and print the array.

In [34]:
l = np.random.uniform(0, 1, 10)

l

array([0.05389364, 0.38860279, 0.30091457, 0.77843805, 0.9934637 ,
       0.40954938, 0.64824593, 0.09370026, 0.33626627, 0.91536648])

* Create a 2D NumPy array of shape (3, 3) with random samples from a normal distribution with mean 0 and standard deviation 1. Print the array.

In [35]:
l = np.random.normal(0, 1, (3, 3))

l

array([[-0.06129701, -1.28215715,  0.80310358],
       [-0.2638277 , -0.50385833,  1.1563603 ],
       [ 0.28867091, -0.79737731,  0.45113645]])

* Create a 1D NumPy array of 20 random integers between 1 and 100. Compute and print the histogram of the array with 5 bins.

In [36]:
l = np.random.randint(1, 101, 20)

hist, bins = np.histogram(l, bins=5)

print(l)
print("Histogram:", hist)
print("Bin :", bins)

[ 67  49  51  32  72 100  59  94  22  38   4  58  36  55  13  64  77  17
  20  57]
Histogram: [5 3 6 4 2]
Bin : [  4.   23.2  42.4  61.6  80.8 100. ]


# Exercise 14: Advanced Indexing and Selection
* Create a 2D NumPy array of shape (5, 5) with random integers between 1 and 20. Select and print the diagonal elements of the array.

In [37]:
l = np.random.randint(1, 21, (5, 5))

diag = np.diagonal(l)

print(l)
print("diag :", diag)

[[10  7 11 17  6]
 [16  5  7  8 18]
 [11 11 19 12  7]
 [16 17 15 10  5]
 [13 15  6 10 13]]
diag : [10  5 19 10 13]


* Create a 1D NumPy array of 10 random integers between 1 and 50. Use advanced indexing to select and print all elements that are prime numbers.

In [38]:
l = np.random.randint(1, 51, size=10)
print(l)

def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

prime_numbers = l[np.vectorize(is_prime)(l)]
print("Prime numbers:", prime_numbers)

[13 12 17 33 16 21  9 45 14 26]
Prime numbers: [13 17]


* Create a 2D NumPy array of shape (4, 4) with random integers between 1 and 10. Select and print all elements that are even numbers.



In [39]:
l = np.random.randint(1, 11, size=(4, 4))
print(l)

even = l[l % 2 == 0]
print("even :", even)

[[4 1 3 4]
 [1 3 7 5]
 [6 9 8 7]
 [1 6 6 8]]
even : [4 4 6 8 6 6 8]


# Exercise 15: Handling Missing Data
* Create a 1D NumPy array of length 10 with random integers between 1 and 10. Introduce np.nan at random positions and print the array.

In [40]:
l = np.random.randint(1, 11, size=10)
print(l)

nan_indices = np.random.choice(l.size, replace=False)
# l[nan_indices] = np.nan
print(nan_indices)

[6 3 3 4 9 9 9 9 6 8]
9


* Create a 2D NumPy array of shape (3, 4) with random integers between 1 and 10. Replace all elements that are less than 5 with np.nan and print the array.

In [41]:
l = np.random.randint(1, 11, size=(3, 4)).astype(float)  
print(l)

l[l < 5] = np.nan

print(l)

[[ 2.  8. 10.  5.]
 [ 3.  9.  7.  9.]
 [ 9.  9.  2. 10.]]
[[nan  8. 10.  5.]
 [nan  9.  7.  9.]
 [ 9.  9. nan 10.]]


* Create a 1D NumPy array of length 15 with random integers between 1 and 20. Identify and print the indices of all np.nan values in the array.

In [42]:
l = np.random.randint(1, 21, size=15).astype(float)  # Converting to float for np.nan

l[[3, 7, 10]] = np.nan

nan_indices = np.where(np.isnan(l))[0]

print("l:\n", l)
print("\nIndices of np.nan values:", nan_indices)

l:
 [16.  8.  9. nan  2. 20. 10. nan  7. 19. nan  1. 19.  4.  7.]

Indices of np.nan values: [ 3  7 10]


# Exercise 16: Performance Optimization with NumPy
* Create a large 1D NumPy array with 1 million random integers between 1 and 100. Compute the mean and standard deviation using NumPy functions and measure the time taken.

In [45]:
import time

l = np.random.randint(1, 101, size=1_000_000)

start = time.time()

mean = np.mean(l)
std_dev = np.std(l)

end = time.time()

print("mean:", mean)
print("standard deviation:", std_dev)
print("temps :", end - start, "seconds")

mean: 50.515523
standard deviation: 28.884092871967972
temps  : 0.0069768428802490234 seconds


* Create two large 2D NumPy arrays of shape (1000, 1000) with random integers between 1 and 10. Perform element-wise addition and measure the time taken.

In [46]:
l = np.random.randint(1, 11, size=(1000, 1000))
l2 = np.random.randint(1, 11, size=(1000, 1000))

start = time.time()

result = l + l2

end = time.time()

print("temp:", end - start, "seconds")

temp: 0.0009965896606445312 seconds


* Create a 3D NumPy array of shape (100, 100, 100) with random integers between 1 and 10. Compute the sum along each axis and measure the time taken.

In [48]:
l = np.random.randint(1, 11, size=(100, 100, 100))
print(l)
start = time.time()

sum_axis0 = np.sum(l, axis=0) 
sum_axis1 = np.sum(l, axis=1) 
sum_axis2 = np.sum(l, axis=2) 

end = time.time()

print("Sum axis 0:", sum_axis0.shape)
print("Sum axis 1:", sum_axis1.shape)
print("Sum axis 2:", sum_axis2.shape)
print("\ntemps:", end - start, "seconds")

[[[ 9 10 10 ...  2 10  8]
  [ 3  1  8 ...  2  7 10]
  [ 5  2  1 ...  5  2  6]
  ...
  [ 1  7  2 ...  4  3  8]
  [ 2 10  5 ...  1  5  9]
  [ 1  3  8 ...  9  5  8]]

 [[ 6  9 10 ...  3  6  1]
  [ 6  5  2 ...  8  5  1]
  [ 4  2  7 ...  3  4  1]
  ...
  [ 8  9  4 ...  1  1  4]
  [ 6  2  4 ...  6  4 10]
  [ 1  6  8 ...  9  2  8]]

 [[ 8  2  8 ...  9  8  7]
  [ 8  1  9 ...  7  1  3]
  [ 7  4  6 ...  2  7  5]
  ...
  [ 7  5  7 ...  7  5  5]
  [ 1 10  5 ...  8  2  6]
  [ 3  9  4 ...  4  3  2]]

 ...

 [[ 3  5  2 ... 10  3  3]
  [ 4  2  8 ...  7 10  3]
  [ 1  8  9 ...  5  4  1]
  ...
  [ 7  5  1 ...  8  8  2]
  [ 8  6  1 ...  3  8  8]
  [ 7 10  8 ...  2  1  8]]

 [[ 4  3  8 ...  6  7  2]
  [ 3  2  9 ...  8  6  2]
  [10  2  8 ...  2  9  6]
  ...
  [ 7 10  9 ...  3  6  9]
  [ 2  2  5 ...  1  5  4]
  [ 7  9  5 ...  6  5  9]]

 [[ 6  6  4 ...  3  7  5]
  [ 5  6  6 ...  5  9 10]
  [ 2  6  4 ...  6  3  6]
  ...
  [ 2  9  6 ... 10  9  2]
  [ 3  1  6 ...  5  9  4]
  [ 2  9  7 ...  2  4  3]]]
Sum axis 0

# Exercise 17: Cumulative and Aggregate Functions
* Create a 1D NumPy array with the numbers from 1 to 10. Compute and print the cumulative sum and cumulative product of the array.



In [49]:
l = np.arange(1, 11)

sum = np.cumsum(l)
product = np.cumprod(l)

print(l)
print("sum:", sum)
print("product:", product)

[[[ 9 10 10 ...  2 10  8]
  [ 3  1  8 ...  2  7 10]
  [ 5  2  1 ...  5  2  6]
  ...
  [ 1  7  2 ...  4  3  8]
  [ 2 10  5 ...  1  5  9]
  [ 1  3  8 ...  9  5  8]]

 [[ 6  9 10 ...  3  6  1]
  [ 6  5  2 ...  8  5  1]
  [ 4  2  7 ...  3  4  1]
  ...
  [ 8  9  4 ...  1  1  4]
  [ 6  2  4 ...  6  4 10]
  [ 1  6  8 ...  9  2  8]]

 [[ 8  2  8 ...  9  8  7]
  [ 8  1  9 ...  7  1  3]
  [ 7  4  6 ...  2  7  5]
  ...
  [ 7  5  7 ...  7  5  5]
  [ 1 10  5 ...  8  2  6]
  [ 3  9  4 ...  4  3  2]]

 ...

 [[ 3  5  2 ... 10  3  3]
  [ 4  2  8 ...  7 10  3]
  [ 1  8  9 ...  5  4  1]
  ...
  [ 7  5  1 ...  8  8  2]
  [ 8  6  1 ...  3  8  8]
  [ 7 10  8 ...  2  1  8]]

 [[ 4  3  8 ...  6  7  2]
  [ 3  2  9 ...  8  6  2]
  [10  2  8 ...  2  9  6]
  ...
  [ 7 10  9 ...  3  6  9]
  [ 2  2  5 ...  1  5  4]
  [ 7  9  5 ...  6  5  9]]

 [[ 6  6  4 ...  3  7  5]
  [ 5  6  6 ...  5  9 10]
  [ 2  6  4 ...  6  3  6]
  ...
  [ 2  9  6 ... 10  9  2]
  [ 3  1  6 ...  5  9  4]
  [ 2  9  7 ...  2  4  3]]]
sum: [ 1  

* Create a 2D NumPy array of shape (4, 4) with random integers between 1 and 20. Compute and print the cumulative sum along the rows and the columns.



In [50]:
l = np.random.randint(1, 21, size=(4, 4))

rows = np.cumsum(l, axis=1)
col = np.cumsum(l, axis=0)

print(l)
print("\nrows:\n", rows)
print("\ncolumns:\n", col)

[[ 8  2 15  8]
 [12 14 20  4]
 [ 3 19 14  4]
 [ 9 20  4 10]]

rows:
 [[ 8 10 25 33]
 [12 26 46 50]
 [ 3 22 36 40]
 [ 9 29 33 43]]

columns:
 [[ 8  2 15  8]
 [20 16 35 12]
 [23 35 49 16]
 [32 55 53 26]]


* Create a 1D NumPy array with 10 random integers between 1 and 50. Compute and print the minimum, maximum, and sum of the array.



In [51]:
l = np.random.randint(1, 51, size=10)

min = np.min(l)
max = np.max(l)
sum = np.sum(l)

print("l:", l)
print("min :", min)
print("max:", max)
print("sum:", sum)

l: [23 23 45 11 46  3 44  1  9 34]
min : 1
max: 46
sum: 239


# Exercise 18: Working with Dates and Times
* Create an array of 10 dates starting from today with a daily frequency and print the array.



In [52]:
today = np.datetime64('today', 'D')
dates = today + np.arange(10) 

print("dates :\n", dates)

dates :
 ['2024-09-24' '2024-09-25' '2024-09-26' '2024-09-27' '2024-09-28'
 '2024-09-29' '2024-09-30' '2024-10-01' '2024-10-02' '2024-10-03']


* Create an array of 5 dates starting from January 1, 2022 with a monthly frequency and print the array.



In [53]:
start = np.datetime64('2022-01-01', 'M') 
dates = start + np.arange(5)  

print("dates :\n", dates)

dates:
 ['2022-01' '2022-02' '2022-03' '2022-04' '2022-05']


* Create a 1D array with 10 random timestamps in the year 2023. Convert the timestamps to NumPy datetime64 objects and print the result.



In [54]:
start = np.datetime64('2023-01-01T00:00')
end = np.datetime64('2024-01-01T00:00')

random = start + np.random.randint(0, (end - start).astype('timedelta64[s]').astype(int), 10)

print("Random timestamps in 2023 as datetime64 objects:\n", random)

Random timestamps in 2023 as datetime64 objects:
 ['2034-03-19T03:44' '2074-05-02T10:15' '2056-11-09T15:42'
 '2050-10-15T00:45' '2044-03-09T22:31' '2066-03-31T18:39'
 '2063-04-08T07:34' '2024-02-28T21:14' '2049-04-02T16:12'
 '2028-01-16T14:48']


# Exercise 19: Creating Arrays with Custom Data Types
* Create a 1D NumPy array of length 5 with custom data type to store integers and their corresponding binary representation as strings. Print the array.



In [55]:
custom_dtype = np.dtype([('number', np.int32), ('binary', 'U10')])

l = np.zeros(5, dtype=custom_dtype)

for i in range(5):
    number = i + 1  # You can use any numbers here
    l[i] = (number, bin(number)[2:])

print(l)

[(1, '1') (2, '10') (3, '11') (4, '100') (5, '101')]


* Create a 2D NumPy array of shape (3, 3) with a custom data type to store complex numbers. Initialize the array with some complex numbers and print the array.



In [57]:
complex = np.dtype('complex')

l = np.array([[1+2j, 3+4j, 5+6j],
            [7+8j, 9+10j, 11+12j],
            [13+14j, 15+16j, 17+18j]], dtype=complex)

print(l)

[[ 1. +2.j  3. +4.j  5. +6.j]
 [ 7. +8.j  9.+10.j 11.+12.j]
 [13.+14.j 15.+16.j 17.+18.j]]


* Create a structured array to store information about books with fields: title (string), author (string), and pages (integer). Add information for three books and print the structured array.

In [60]:
book_dtype = np.dtype([('titre', 'U100'), 
                       ('auteur', 'U100'),
                       ('pages', np.int32)])  

livre = np.zeros(3, dtype=book_dtype)

livre[0] = ('titre1', 'auteur1', 322)
livre[1] = ('titre2', 'auteur2', 433)
livre[2] = ('titre3', 'auteur3', 444)

# Print the structured array
print(livre)

[('titre1', 'auteur1', 180) ('titre2', 'auteur2', 328)
 ('titre3', 'auteur3', 281)]
